name: Android build CI

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: prebuilt
      run: |
        sed -i -e '/google-services/d; /firebase/d' build.gradle
        sed -i -e '/google-services/d; /firebase/d' app/build.gradle
        sed -i -e '/FirebaseAnalytics.getInstance/,+3d' app/src/main/java/ceui/lisa/activities/Shaft.java
        sed -i -e '/baseBind.isFirebaseEnable.setChecked/,+9d' app/src/main/java/ceui/lisa/fragments/FragmentSettings.java
        sed -i -e '/firebase/d' app/src/main/java/ceui/lisa/activities/Shaft.java app/src/main/java/ceui/lisa/fragments/FragmentSettings.java 
    - name: Build with Gradle
      run: |
         chmod +x gradlew
         ./gradlew assembleRelease
    - name: Sign app APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties
    - name : upload apk
      uses: actions/upload-artifact@master
      if: always()
      with:
        path: "app/build/outputs/apk/release/*-signed.apk"
    - name: Send commit to telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |+
          New push to github!
          *${{ github.event.head_commit.message }}* by ${{ github.event.head_commit.author.name }}
          See commit detail [here](${{ github.event.head_commit.url }})
        document: "app/build/outputs/apk/release/*-signed.apk"
